# commit to be tagged for new release
commit = "HEAD"

# project_name is used to refer to the project in the notes
project_name = "containerd"

# github_repo is the github project, only github is currently supported
github_repo = "containerd/containerd"

# match_deps is a pattern to determine which dependencies should be included
# as part of this release. The changelog will also include changes for these
# dependencies based on the change in the dependency's version.
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release of this project for determining changes
previous = "v1.7.10"

# pre_release is whether to include a disclaimer about being a pre-release
pre_release = false

# preface is the description of the release which precedes the author list
# and changelog. This description could include highlights as well as any
# description of changes. Use markdown formatting.
preface = """\
The eleventh patch release for containerd 1.7 contains various fixes and updates.

### Notable Updates

* **Don't block snapshot garbage collection on Remove failures** ([#9482](https://github.com/containerd/containerd/pull/9482))
* **Add warning for CRIU config usage** ([#9481](https://github.com/containerd/containerd/pull/9481))
* **Fix otel version incompatibility** ([#9483](https://github.com/containerd/containerd/pull/9483))
* **Add cri-api v1alpha2 usage warning to all api calls** ([#9479](https://github.com/containerd/containerd/pull/9479))
* **cri: add deprecation warnings for deprecated CRI configs** ([#9469](https://github.com/containerd/containerd/pull/9469))
* **runtime/v2: net.Dial gRPC shim sockets before trying grpc**([#9458](https://github.com/containerd/containerd/pull/9458))
* **tasks: emit warning for v1 runtime and runc v1 runtime** ([#9450](https://github.com/containerd/containerd/pull/9450))
* **push: always inherit distribution sources from parent** ([#9452](https://github.com/containerd/containerd/pull/9452))
* **Update tar tests to run on Darwin** ([#9451](https://github.com/containerd/containerd/pull/9451))
* **ctr: Add sandbox flag to ctr run** ([#9449](https://github.com/containerd/containerd/pull/9449))
* **Windows default path overwrite fix** ([#9440](https://github.com/containerd/containerd/pull/9440))
* **snapshots: emit deprecation warning for aufs** ([#9436](https://github.com/containerd/containerd/pull/9436))

See the changelog for complete list of changes"""